package com.tingfeng.model;
// Generated 2015-2-11 21:18:51 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin")
public class Admin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Date lastLoginTime;
	private String name;
	private String password;
	/**
	 * 此管理员的称呼,比如系统管理员
	 */
    private String nickName;
	/**
	 * 所有的权利值都>=0,系统管理员权限值为0,权力值越小,权利越大
	 */
	private Integer powerValue;

	public Admin() {
	}

	public Admin(String name, String password, Integer powerValue) {
		this.name = name;
		this.password = password;
		this.powerValue = powerValue;
	}


	@Column(nullable = false, length = 50)
	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLoginTime", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "name", nullable = false,unique = true, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}


	@Column(name = "powerValue", nullable = false)
	public Integer getPowerValue() {
		return this.powerValue;
	}

	public void setPowerValue(Integer powerValue) {
		this.powerValue = powerValue;
	}

}
