// default package
// Generated 2014-10-10 11:04:57 by Hibernate Tools 3.4.0.CR1
package com.tingfeng.model;

import java.lang.annotation.Inherited;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Story generated by hbm2java 保存小说和小说榜单中小说需要的一些,自身的一些属性
 */
public abstract class BaseStory implements java.io.Serializable {
	/**
	 * 
	 */
	protected static final long serialVersionUID = 2886812425473071282L;
	protected Long id;
	protected String name;
	protected String author;
	/**
	 * 小说已写的字数,分为几个级别:
	 *  1('微型小说(1到千字)');2 ('20', '短篇小说(千~万字)');3 ('21','短中小说(1万~10万字)');
	 *  4 ('22', '中篇小说(10万~50万字)');5 ('23','中长小说(50万~200万字)');
	 *  6 ('24', '长篇小说(200万~500万字)'); 7 ('25','超长小说(>500万字)');8(未完结,字数未知)
	 */
	protected Integer wordCount;
	/**
	 * 更新状态,1表示完结,2表示持续更新,3表示其它
	 */
	protected Integer updateState;
	protected String image;
	/**
	 * 出版小说的时间
	 */
	protected Date publishedTime;
	/**
	 * 小说的完结时间,仅当updateState为1的时候生效
	 */
	protected Date endTime;
	
	/**
	 * 小说评分,总分,所有人累计的分值;
	 */
	protected Long score;
	/**
	 * 平均分
	 */
	protected double avgScore;
	/**
	 * 评分的次数
	 */
	protected Long markCount;
	/**
	 * 百度百科的url,可以不填写
	 */
	protected String storyBaikeUrl;
	
	protected StoryType storyType;
	
	public BaseStory() {
	}	
	@ManyToOne
	@JoinColumn(name="storyTypeId",nullable = false)
	public StoryType getStoryType() {
		return storyType;
	}

	public void setStoryType(StoryType storyType) {
		this.storyType = storyType;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false,length=50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "author",length=50)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Integer getUpdateState() {
		return updateState;
	}

	public Date getEndTime() {
		return endTime;
	}

	public Integer getWordCount(){
		if(updateState==null||updateState==2||updateState==3)
			wordCount=8;
		return this.wordCount;
	}
	
	public void setWordCount(Integer wordCount) {
		if(updateState==null||updateState==2||updateState==3)
			wordCount=8;
		this.wordCount = wordCount;
	}

	public void setUpdateState(Integer updateState) {
		this.updateState = updateState;
	}
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public double getAvgScore() {
		return avgScore;
	}

	public void setAvgScore(double avgScore) {
		this.avgScore = avgScore;
	}

	@Column(name = "image",length=255)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publishedTime", nullable = false, length = 19)
	public Date getPublishedTime() {
		return publishedTime;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}
	public Long getScore() {
		return score;
	}
	public Long getMarkCount() {
		return markCount;
	}
	public String getStoryBaikeUrl() {
		return storyBaikeUrl;
	}
	public void setScore(Long score) {
		this.score = score;
	}
	public void setMarkCount(Long markCount) {
		this.markCount = markCount;
	}
	public void setStoryBaikeUrl(String storyBaikeUrl) {
		this.storyBaikeUrl = storyBaikeUrl;
	}
	@Override
	public int hashCode() {
		return this.getId().intValue();
	}
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof BaseStory)
		{   BaseStory o=((BaseStory)obj);
			
			if(o.getId()-this.getId()==0)
				return true;
			if(o.getAuthor().equals(this.getAuthor())&&o.getName().equals(this.getName()))
				return true;
		}
		return false;
	}		
    
}
