// default package
// Generated 2014-10-10 11:04:57 by Hibernate Tools 3.4.0.CR1
package com.tingfeng.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Story generated by hbm2java 保存小说自身的一些属性
 */
@Entity
@Table(name = "story")
public class Story extends BaseStory implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2886812425473071282L;
	/**
	 * 当errorCount评论次数从0到1的时候,记录其评论次数,
	 * 这个记录实际上
	 */
	private Long markCountWhenCorrect;
	/**
	 * 认为小说信息错误的次数
	 */
	private Integer errorCount;
	/**
	 * 当errorCount评论次数从0到1的时候,记录其评论时间
	 */
	private Date correctTime;
	
	private Integer status;
	
	public Story() {
	}
	public Story(Long id) {
		super.setId(id);
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Long getMarkCountWhenCorrect() {
		return markCountWhenCorrect;
	}
	public void setMarkCountWhenCorrect(Long markCountWhenCorrect) {
		this.markCountWhenCorrect = markCountWhenCorrect;
	}
	public Integer getErrorCount() {
		return errorCount;
	}

	public Date getCorrectTime() {
		return correctTime;
	}

	public void setErrorCount(Integer errorCount) {
		this.errorCount = errorCount;
	}

	public void setCorrectTime(Date correctTime) {
		this.correctTime = correctTime;
	}
	@ManyToOne
	@JoinColumn(name="storyTypeId",nullable = false)
	public StoryType getStoryType() {
		return storyType;
	}

	public void setStoryType(StoryType storyType) {
		this.storyType = storyType;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false,length=50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "author",length=50)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Integer getUpdateState() {
		return updateState;
	}

	public Date getEndTime() {
		return endTime;
	}

	public Integer getWordCount(){
		if(updateState==null||updateState==2||updateState==3)
			wordCount=8;
		return this.wordCount;
	}
	
	public void setWordCount(Integer wordCount) {
		if(updateState==null||updateState==2||updateState==3)
			wordCount=8;
		this.wordCount = wordCount;
	}

	public void setUpdateState(Integer updateState) {
		this.updateState = updateState;
	}
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "image",length=255)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publishedTime", nullable = false, length = 19)
	public Date getPublishedTime() {
		return publishedTime;
	}	
	@Column(nullable = false)
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}
	public Long getScore() {
		return score;
	}
	public Long getMarkCount() {
		return markCount;
	}
	public String getStoryBaikeUrl() {
		return storyBaikeUrl;
	}
	public void setScore(Long score) {
		this.score = score;
	}
	public void setMarkCount(Long markCount) {
		this.markCount = markCount;
	}
	public void setStoryBaikeUrl(String storyBaikeUrl) {
		this.storyBaikeUrl = storyBaikeUrl;
	}
	
}
