// default package
// Generated 2014-10-10 11:04:57 by Hibernate Tools 3.4.0.CR1
package com.tingfeng.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Storytype generated by hbm2java
 * 小说的种类
 */
@Entity
@Table(name = "storyType")
public class StoryType implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String name;

	public StoryType() {
	}

	public StoryType(String name) {
		this.name = name;
	}
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
